version: '3.1'

services:
  db-test:
    image: postgres
    restart: always
    ports:
      - "5433:5432" # ← Use different port to avoid conflict
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
    volumes:
      - "./test-sql:/docker-entrypoint-initdb.d" # ← Separate test SQL folder
